[maas]
localhost ansible_connection=local

[librenms]
192.168.7.157 ansible_user=ubuntu

[docker]
192.168.7.12 ansible_user=itadmin

[Ubuntu]
192.168.7.60 anisble_user=itadmin
192.168.7.61 ansible_user=itadmin
192.168.7.62 ansible_user=itadmin
192.168.7.63 ansible_user=itadmin
192.168.7.64 ansible_user=itadmin
192.168.7.65 ansible_user=itadmin
192.168.7.103 ansible_user=ubuntu
192.168.7.107 ansible_user=ubuntu
192.168.7.118 ansible_user=ubuntu

[k3s_server]
192.168.7.169

[k3s_worker]
192.168.7.103
192.168.7.107
192.168.7.118

[k3s_cluster:children]
k3s_server
k3s_worker

[k3s_cluster:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519

[windows]
192.168.7.215

[windows:vars]
ansible_user=.\itadmin
ansible_password="27T3ch##"
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_port=5985

[all:vars]
ansible_python_interpreter=/usr/bin/python3
