---
- name: Sæt trunk-port på Cisco switch
  hosts: "{{ switch }}"
  gather_facts: no

  tasks:
    - name: Konfigurer trunk-port
      cisco.ios.ios_config:
        parents: "interface {{ interface }}"
        lines:
          - description {{ description }}
          - switchport mode trunk
          - switchport trunk allowed vlan {{ allowed_vlans }}
          - no shutdown
