---
- name: Sæt access-port på Cisco switch
  hosts: "{{ switch }}"
  gather_facts: no

  tasks:
    - name: Konfigurer access-port
      cisco.ios.ios_config:
        parents: "interface {{ interface }}"
        lines:
          - description {{ description }}
          - switchport mode access
          - switchport access vlan {{ vlan_id }}
          - spanning-tree portfast
          - no shutdown
