- name: Join workers to k3s
  hosts: k3s_worker
  become: true
  vars:
    k3s_server_ip: "{{ hostvars[groups['k3s_server'][0]]['ansible_host'] }}"
    k3s_token: "{{ hostvars[groups['k3s_server'][0]]['k3s_join_token'] }}"
  tasks:
    - name: Install k3s agent
      shell: |
        curl -sfL https://get.k3s.io | \
        K3S_URL="https://{{ k3s_server_ip }}:6443" \
        K3S_TOKEN="{{ k3s_token }}" sh -
      args:
        creates: /etc/systemd/system/k3s-agent.service
