- name: Ping Linux hosts
  hosts: ubuntu:docker:librenms:maas
  gather_facts: false
  tasks:
    - name: Ping Linux
      ansible.builtin.ping:

- name: Ping Windows hosts
  hosts: windows
  gather_facts: false
  tasks:
    - name: Ping Windows
      ansible.windows.win_ping:
